---
title: "Autocompletion"
output: teachdown::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(teachdown)
library(nycflights13)
options(teachdown.event_recorder = teachdown:::debug_event_recorder)
teachdown_options(
  exercise.eval = FALSE, 
  exercise.checker = function(label, user_code, envir_result, ...)  {
    if (is.null(envir_result))
      list(message = "Bad code!",
           correct = FALSE)
    else
      list(message = "Nice job!", 
           correct = TRUE, 
           location = "append")
  },
  exercise.completion = TRUE,
  exercise.diagnostics = TRUE
)
```

## Autocompletion Sandbox

```{r autocompletion-setup}
autocompletion <- list(apple = 1, banana = 2, cherry = 3)
```

```{r autocompletion, exercise=TRUE, exercise.completion = TRUE, exercise.setup="autocompletion-setup"}
# Try typing here
```

```{r autocompletion2, exercise=TRUE}
# Try typing here
```

```{r no-diagnostics, exercise=TRUE, exercise.diagnostics=FALSE}
# no diagnostics here
```

```{r diagnostics, exercise=TRUE}
# diagnostics here
```

