---
title: "Chained setup chunks: Cycles"
author: "Nischal Shrestha"
output: learnr::tutorial
runtime: shiny_prerendered 
description: > 
  This is a demo of catching cyclic dependencies with chained setup chunks.
---

```{r setup, include = FALSE}
library(reticulate)
library(learnr)
library(gradethis)
knitr::opts_chunk$set(echo = FALSE) 
tutorial_options(exercise.checker = gradethis::grade_learnr) 
d <- 3
```

# Addition

<!-- Test that cyclic dependencies are detected: feel free to try different cycles here -->

```{r dataA}
a <- 5
```

```{r dataB, exercise.setup = "dataA"}
b <- a + d
``` 

<!-- TODO: for some reason setting this first data1's exercise.setup to anything else causes an object 'b' not found error -->

```{r dataC, exercise.setup = "dataB"}
c <- b
```

Result of w should be 9.

```{r data1, exercise=TRUE, exercise.setup = "dataC"}
w = c + 1

```

<!-- We should detect a cycle for data2 (data2 => data4 => data3 => data2) here and an error message upon processing this Rmd -->
Result of x should be 10.

```{r data2, exercise=TRUE, exercise.setup = "data4"}
x <- w + 1

```

Result of y should be 11.

```{r data3, exercise=as.logical(1), exercise.setup = "data2"}
y <- x + 1

```

Result of z should be 12.

```{r data4, exercise=TRUE, exercise.setup = "data3"}
z <- y + 1

```

