owd <- getwd()

ROOT <- rprojroot::find_package_root_file()
ACE_VERSION <- "1.2.6"
ACE_FILES <- c(
  "ace.js",
  "ext-language_tools.js",
  "mode-css.js",
  "mode-html.js",
  "mode-javascript.js",
  "mode-plain_text.js",
  "mode-r.js",
  "mode-rdoc.js",
  "mode-rhtml.js",
  "mode-text.js",
  "mode-xml.js",
  "theme-textmate.js"
)

url <- sprintf(
  "https://github.com/ajaxorg/ace-builds/archive/v%s.tar.gz",
  ACE_VERSION
)

destfile <- tempfile("ace-tarball-")
download.file(url, destfile = destfile)

exdir <- tempfile("ace-")
dir.create(exdir)
untar(tarfile = destfile, exdir = exdir)

setwd(exdir)
setwd(sprintf("ace-builds-%s", ACE_VERSION))

source <- file.path("src", ACE_FILES)
contents <- paste(lapply(source, function(file) {
  readChar(file, file.info(file)$size, TRUE)
}), collapse = "\n")

target <- file.path(ROOT, "inst/lib/ace/ace.js")
writeLines(contents, con = target, sep = "\n", useBytes = TRUE)

metadata <- c(
  "# This file was autogenerated by 'tools/update-ace.R'",
  paste("ACE_VERSION <-", shQuote(ACE_VERSION))
)

writeLines(metadata, con = file.path(ROOT, "R/ace.R"))

unlink(destfile)
unlink(exdir, recursive = TRUE)
setwd(owd)