on:
  push:
    branches:
      - master
      - ghactions

name: Deploy

jobs:

  # added so that the workflow doesn't fail.
  always_runner:
    runs-on: ubuntu-latest
    steps:
      - name: Always run
        run: echo "This job is used to prevent the workflow status from showing as failed when all other jobs are skipped"


  deploy:
    if: github.repository == 'rstudio/learnr'
    runs-on: ${{ matrix.config.os }}

    name: "shinyapps.io"

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-16.04, r: '3.6', cran: "https://demo.rstudiopm.com/all/__linux__/xenial/latest"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.cran }}

    steps:
      - uses: actions/checkout@v1

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: >
          Rscript
          -e "install.packages('remotes')"
          -e "saveRDS(remotes::dev_package_deps(dependencies = TRUE), 'depends.Rds', version = 2)"

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-deploy-${{ hashFiles('depends.Rds') }}
          restore-keys: |
            ${{ runner.os }}-r-${{ matrix.config.r }}-deploy-
            ${{ runner.os }}-r-${{ matrix.config.r }}-

      - name: Install dependencies
        run: >
          Rscript
          -e "library(remotes)"
          -e "update(readRDS('depends.Rds'))"
          -e "remotes::install_cran('sortable')"

      - name: Deploy
        run: >
          Rscript 'tools/deploy_tutorials_on_ci.R'
