name: pkgdown-pr-cleanup

on:
  pull_request:
    types: [closed]

jobs:
  pkgdown-pr-cleanup:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "gh-pages"

      - name: Clean up PR Preview
        env:
          PR_NUMBER: "${{ github.event.pull_request.number }}"
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"

          preview_dir="preview/pr${PR_NUMBER}"
          if [ -d "$preview_dir" ]; then
            git rm -r $preview_dir
            git commit -m "Remove $preview_dir (GitHub Actions)" || echo 'No preview to remove'
            git push origin || echo 'No preview to remove'
          else
            echo 'No preview to remove'
          fi

